# Generated by Django 4.0.4 on 2022-04-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='stores',
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ManyToManyField(to='api_store.store'),
        ),
    ]
